project4/app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('India/',India,name='India'),
]

project4/project4/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
from app2.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('America/',America,name='America'),
    path('app1/',include('app1.urls')),
]

project4/app1/models.py
from django.db import models

# Create your models here.

project4/app2/models.py
from django.db import models

# Create your models here.

project4/app1/views.py
from django.shortcuts import render

# Create your views here.
def India(request):
    
    return render(request,'India.html')

project4/app2/views.py
from django.shortcuts import render

# Create your views here.
def America(request):
    
    return render(request,'America.html')

def India(request):
    
    return render(request,'India.html')

project4/templates/America.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h1{
            background-color: aqua;
        }
        
    </style>
</head>
<body>
    <center>
        <h1>this is America page</h1>
        <a href="{% url 'app1:India' %}"> navigate to India</a>
    </center>
</body>
</html>

project4/templates/India.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h1{
            background-color: aquamarine;
        }
    </style>
</head> 
<body>
    <center>
        <h1>this is india</h1>
        <a href="{% url 'America' %}"> navigate to America</a>
    </center>
</body>
</html>